[package]
name = "nuclear_throne_ai"
version = "0.1.0"
authors = ["Lilith645 <lilith@inet-sys.com>"]

[dependencies]
enigo = { path = "./enigo-rs/"}
bmp = "*"
image = "*"
screenshot = { path = "./screenshot-rs/"}
rand = "*"
